ingredients = ['Beans', 'Sugar', 'Cocoa Butter', 'Lecithin', 'Vanilla', 'Salt', 'Sweetener other than white cane or beet sugar'];
flavours = ['oily',
    'classic',
    'spice',
    'ripe',
    'banana',
    'wtf',
    'mild tart',
    'deep cocoa',
    'mild off',
    'red berry',
    'chewy',
    'malt',
    'tart',
    'metal',
    'spicy',
    'smokey',
    'odd',
    'burnt',
    'dark woody',
    'herbs',
    'anise',
    'nut',
    'almond',
    'grit',
    'rubber',
    'metallic',
    'black tea',
    'soil',
    'cocoa',
    'sweet',
    'fudgey',
    'coffee',
    'woody',
    'grass',
    'wood',
    'honey',
    'bitter',
    'muted',
    'deep',
    'cherries',
    'cheesy',
    'chalky',
    'meaty',
    'sandy',
    'deep cherry',
    'silky',
    'grain',
    'intense tart',
    'slow',
    'apple',
    'fig',
    'cigar',
    'cooling sensation',
    'dry',
    'pudding',
    'licorice',
    'ham',
    'green',
    'mint',
    'fat',
    'bright',
    'choco',
    'mild ham',
    'pastey',
    'molasses',
    'strong',
    'floral',
    'smoke',
    'thick',
    'rich cocoa',
    'nuts',
    'sharp',
    'rustic',
    'grainy',
    'orange',
    'accesible',
    'subtle',
    'dirt',
    'oats',
    'plums',
    'salt',
    'sticky',
    'fuel',
    'tart fruit',
    'dairy',
    'leather',
    'dull',
    'hay',
    'acidic',
    'palm',
    'undefined',
    'burlap',
    'plum',
    'lime',
    'balanced',
    'coarse',
    'peanut',
    'basic',
    'pepper',
    'berry',
    'rubbery',
    'rum',
    'chemical',
    'pure',
    'complex',
    'vanilla',
    'powdery',
    'rich malt',
    'cashew',
    'grits',
    'roasted',
    'long',
    'creamy',
    'toast',
    'unique',
    'baked',
    'perfume',
    'off flavor',
    'gritty',
    'masculine',
    'fertilzer',
    'gateway',
    'empty',
    'long lasting',
    'dominant spice',
    'maple',
    'synthetic',
    'intense',
    'soapy',
    'soap',
    'dates',
    'winey',
    'burn',
    'bold',
    'strawberry',
    'mild bitter',
    'tang',
    'mild mint',
    'unbalanced',
    'off notes',
    'mild',
    'wine',
    'delicate',
    'olive',
    'off note',
    'mild floral',
    'sugary',
    'wild berry',
    'unfixable',
    'late tart',
    'musty',
    'diluted',
    'med roast',
    'tropical',
    '',
    'robust',
    'sour milk',
    'cheese',
    'berries',
    'high roast',
    'grape',
    'oreo shell',
    'hammy',
    'dense',
    'hebs',
    'mold',
    'hot cocoa',
    'alocohol',
    'moss',
    'soy',
    'mushroom',
    'chlorine',
    'uneven',
    'raw',
    'tea',
    'flat',
    'cherry',
    'spicy edge',
    'melon',
    'fungal',
    'sour',
    'sl. Sour',
    'yogurt',
    'cucumber',
    'one dimensional',
    'sunflower',
    'harsh',
    'rich',
    'tannic',
    'ambiguous',
    'petro',
    'leafy',
    'swiss miss',
    'off',
    'simple',
    'off aroma',
    'charcoal',
    'tobacco',
    'gummy',
    'cream'
];