ingredients = ['Beans', 'Sugar', 'Cocoa Butter', 'Lecithin', 'Vanilla', 'Salt', 'Sweetener other than white cane or beet sugar'];
flavours = ['molasses',
    'sour ending',
    'sweet spices',
    'muted spice',
    'full cocoa flavor',
    'sticky',
    'dominant tobacco',
    'mild licorice',
    'mild earthy',
    'slight ashy',
    'cooling sensation',
    'herbs',
    'spice',
    'crisp nibs',
    'light roast',
    'creamy',
    'smokey',
    'red berry',
    'cashew',
    'tang',
    'honey with subtle tobacco',
    'intense spice',
    'sl. Burnt',
    'sour fig',
    'peanut butter',
    'possible mold',
    'fig',
    'off',
    'intense smoke',
    'tart',
    'tart red berry',
    'acidic',
    'powerful',
    'grape',
    'herb',
    'rich mocha',
    'strong floral',
    'bland',
    'grass',
    'strong chemical',
    'gummy',
    'grit',
    'sweet edge',
    'off aroma',
    'rum',
    'chalky',
    'orange',
    'mild mint',
    'oily',
    'gentle roast',
    'dark fruit',
    'fatty',
    'nuts',
    'balanced',
    'home baked banana nut bread',
    'rubber',
    'short',
    'mild tobacco',
    'mint',
    'grapes',
    'subtle dairy',
    'complex',
    'off flavor',
    'grits',
    'dirty',
    'homey',
    'heavy roast',
    'black pepper and banana',
    'leather',
    'hay',
    'off note',
    'dirt',
    'mild coffee',
    'bold',
    'mild fruit',
    'long lasting',
    'metal',
    'artificial',
    'pastey',
    'plum',
    'cherry',
    'high astringency',
    'fuel',
    'strong spice',
    'candy like',
    'dense',
    'mild ashey',
    'distinct',
    'pure',
    'light color',
    'honey',
    'grainy',
    'simple',
    'roasted banana',
    'yogurt',
    'hebs',
    'dates',
    'maple',
    'gateway',
    'savory',
    'rustic',
    'charcoal',
    'rubbery',
    'delicate fruit',
    'burlap',
    'alocohol',
    'toast',
    'mild molasses',
    'cooked banana',
    'clingy',
    'late tart',
    'subtle',
    'flat',
    'wine',
    'cucumber',
    'undefined',
    'soapy',
    'fertilzer',
    'tea',
    'olive',
    'gritty',
    'diluted',
    'strong roast',
    'bitter aftertaste',
    'strong cocoa',
    'vinegar',
    'cocoa and powerful tang',
    'cheese',
    'nut',
    'roasty undertone',
    'accesible',
    'berries',
    'petro',
    'harsh burnt',
    'mild bitter',
    'thick',
    'fungal',
    'swiss miss',
    'anise',
    'strawberry',
    'papaya',
    'powdery',
    'robust',
    'roast dominates',
    'intense plum',
    'candy flavor',
    'unbalanced',
    'mild choco',
    'walnut',
    'burning',
    'vanilla',
    'muddy',
    'large grits',
    'spoiled milk',
    'moldy',
    'lime',
    'cheesy',
    'melon',
    'musty',
    'soy',
    'basic',
    'non descript',
    'aluminum',
    'brownie batter',
    'spicy and rich',
    'grainy texture',
    'cigar',
    'mold',
    'moss',
    'dull',
    'dutched?',
    'watering',
    'light perfume',
    'tropical',
    'uneven melt',
    'low refinement',
    'hammy',
    'clean',
    'mild fatty',
    'classic',
    'intens',
    'meaty',
    'unripe fruit',
    'alcohol',
    'ambiguous',
    'menthol',
    'green apple',
    'masculine',
    'clove',
    'brownie mix',
    'chlorine',
    'salt',
    'unfixable',
    'slow develop',
    'hot spice',
    'bread',
    'strong bitter',
    'med roast',
    'fat residue',
    'mysterious',
    'wtf',
    'mushroom',
    'harsh',
    'earth',
    'ginger',
    'tobacco',
    'slight hammy',
    'bright red fruit',
    'floral',
    'high astringcy',
    'sharp',
    'strong coffee',
    'true to sugar bar',
    'sour tart plum',
    'simple cocoa note',
    'wheat',
    'why bother',
    'punchy',
    'intense cocoa',
    'nuanced',
    'unique flavor',
    'strong fruit',
    'strong smokey tobacco',
    'rough',
    'pasty',
    '',
    'high astringent',
    'dairy',
    'delicate',
    'nibs too soft',
    'bold olive',
    'vanilla(n)',
    'mild nutty & woody',
    'green',
    'large nibs',
    'empty',
    'rounded',
    'carrots',
    'intense olive',
    'wet',
    'intense spicy',
    'long',
    'fig w/ floral undertone',
    'baked',
    'alluring aroma',
    'late cocoa notes',
    'flour',
    'modest',
    'surface mark',
    'cocoa and fresh grapes',
    'winey',
    'cough medicine',
    'tangy wine',
    'mild vanilla and mild fruit',
    'notes from sugar',
    'full bodied',
    'high acidity',
    'cherries',
    'unrecognizable',
    'bourbon',
    'espresso',
    'late sour & molasses',
    'hint of tang',
    'mild metallic',
    'pepper',
    'deep cocoa',
    'hot cocoa',
    'coffee notes from roaster',
    'strong',
    'sl. Sour',
    'sandy',
    'wild berry',
    'prunes',
    'slightly dry and super spicey',
    'banana',
    'super temper',
    'light brown',
    'cream',
    'intense brownie',
    'intense floral',
    'sandy texture',
    'strong vanilla',
    'light rum',
    'fat',
    'fig notes',
    'coffee ground',
    'spoiled',
    'lacks development',
    'black tea',
    'nibs add bitterness',
    'spicy pepper',
    'slight harsh molasses',
    'strong rubber',
    'strong nutty',
    'Cadbury egg',
    'mild smoke',
    'fades fast',
    'sugar dominates',
    'deep',
    'long and rich',
    'subtle fruit then cocoa',
    'mild sweet cocoa',
    'slight bitter',
    'sour banana',
    'dark berry',
    'spicy and fragrant',
    'roasty and under refined',
    'mild sour orange',
    'mild cherry',
    'brief fruit note',
    'slight burnt',
    'vanilla dominates',
    'mild hammy',
    'full body',
    'milk brownie',
    'true to origin',
    'high roast',
    'mild ham',
    'late spiciness',
    'roasted pear',
    'plums',
    'uneven',
    'sour dairy',
    'poor finish',
    'intense marshmallow',
    'large unground pieces',
    'black pepper',
    'mild musty',
    'Easter candy',
    'waxy mouthfeel',
    'bitter then nutty rustic',
    'black current',
    'metallic edge',
    'late floral',
    'ham-like',
    'high acid',
    'burn',
    'rich choco',
    'mild lemon',
    'ham',
    'sour notes',
    'mild rubber',
    'bitter coffee flavor',
    'late hammy',
    'tart with woody undertones',
    'intense',
    'base cocoa w/ palm notes',
    'sour milk',
    'spicy',
    'savory lemon',
    'bold cherry',
    'unique',
    'chunky melt',
    'salt noticeable',
    'subtle but refreshing',
    'dirty/burnt edge',
    'mild floral',
    'caramel "rolo"',
    'blueberry & cocoa dominate',
    'few grits',
    'light toffee',
    'smoke dominates',
    'melon floral',
    'multiple off flavors',
    'pungent raisin',
    'sl. Hammy',
    'rich',
    'sour veggie',
    'refined',
    'bright',
    'mild dairy',
    'chemical off',
    'uncontrolled bitterness',
    'spices',
    'intense grapes',
    'smooth texture',
    'simple red berry',
    'intense tart',
    'slight woody',
    'roasted',
    'candy spices',
    'sour mint',
    'mellow choco',
    'green mint',
    'fall spices',
    'fruit punch',
    'mellow but flavorful',
    'mild burn',
    'rich fruit',
    'extra sweet',
    'floral-spice mix',
    'harsh flavor',
    'butter',
    'spicy edge',
    'rubber off',
    'red wine',
    'tolerable bitter',
    'pure cocoa',
    'distinct spicey',
    'single note',
    'bread notes',
    'harsh aroma',
    'vegetable and honey',
    'melon like',
    'banana cream',
    'ligt color',
    'intense sweet',
    'earthy green',
    'intense prune and berry',
    'slight grainy',
    'sour malt',
    'hint of smoke',
    'strong molasses',
    'sour tang',
    'poor aftertaste',
    'intense vinegar',
    'orange peel',
    'mild spice',
    'chocolate ice cream',
    'mellow fruit',
    'delicate cocoa',
    'tea-like',
    'sl. bitter up front',
    'harsh earthiness',
    'grapes and honey',
    'fresh nibs',
    'some roasty notes',
    'roasted cocoa',
    'mild roasty',
    'dominant hazelnut',
    'intense coffee',
    'harsh ending',
    'mild smoke and fruit',
    'strong start',
    'brownie like',
    'slight dry',
    'sublte grape notes',
    'sour off flavor',
    'intense pepper',
    'wood',
    'slight burnt note',
    'burnt',
    'spice/herb dominate cocoa base',
    'roasty edge',
    'harsh smoke',
    'strong smoke',
    'intense banana',
    'sharp fruit',
    'earthy ending',
    'ultra fruity',
    'mild honey',
    'melon notes',
    'medium roasted cocoa',
    'odd dairy',
    'chocolate base off',
    'sublte strawberry',
    'tropical fruit',
    'pungent grape',
    'chemical or burnt note',
    'chocolate covered cherries',
    'nutty and bitter dominate',
    'heavy smoke',
    'mild off',
    'candy tart',
    'coarse',
    'mild berry',
    'basic chocolate',
    'molasses undertone',
    'tart fruit',
    'intense earthy',
    'dominant savory',
    'sour vanila',
    'vanilla domintates',
    'flat flavor',
    'short length',
    'leathery flavor',
    'dark roast',
    'basic cocoa',
    'cocoa base',
    'chocolate covered banana',
    'dominant spice',
    'spicy cinnamon',
    'prominent plum note',
    'pudding',
    'strong pepper',
    'fruit forward',
    'coffee grounds',
    'strong spicey',
    'cocoa and coconut',
    'alkalyzed notes',
    'fruit medley',
    'dried fruit (fig)',
    'strong off flavor',
    'lemon',
    'intense vanilla',
    'strong choco',
    'sour grapes',
    'tart citrus',
    'deep choco',
    'mild profile',
    'strong raspberry',
    'ripe',
    'green fruit',
    'rich brownie',
    'slight sour',
    'tart raspberry',
    'slight metallic',
    'slight musty',
    'easy melt',
    'rich cooa',
    'intense bitter',
    'robust dark tropical fruit',
    'full flavor spectrum',
    'too few nibs',
    'almond butter',
    'mild banana',
    'chocolate milk',
    'dark color',
    'unripened fruit',
    'strong malt',
    'mild anise',
    'slight plum',
    'spicy and candy-like',
    'woody',
    'berry notes with sweet edge',
    'mild off note',
    'rich cocoa dominates',
    'mild nutty',
    'mild flavors',
    'roasted cherry',
    'wild berries',
    'bright red',
    'faint cinnamon',
    'dominant roast',
    'robust cocoa',
    'fudge-like',
    'dominate cocoa notes',
    'bright berry',
    'mild tannic',
    'yellow fruit',
    'mild coffee and rum',
    'slight roasty',
    'sweet cocoa',
    'bright fruit',
    'non-descript',
    'mild woody',
    'fruity with coffee notes',
    'mild pear',
    'mild nutty and fruit',
    'mild bitter and chemical off',
    'harsh woody',
    'late spice notes',
    'slow',
    'sour',
    'intense blueberry',
    'sour orange',
    'subtle red berry',
    'spicy mild molasses',
    'roasted strawberry',
    'assertive',
    'subtle fruit',
    'off sour note',
    'mild sour',
    'rich hot cocoa',
    'late tart notes',
    'mild cocoa',
    'evolves black pepper to citrus',
    'simple cocoa',
    'cocoa dominates',
    'mild orange',
    'less intense berry',
    'off notes of rubber',
    'red fruit',
    'sour raisin',
    'strong distinct spice',
    'mild vanilla',
    'intense mocha flavor',
    'tropical fruit and mild smoke',
    'mild sweet honey',
    'poor texture',
    'strong wine',
    'soil',
    'sweet grass',
    'chemical',
    'cocoa',
    'one dimensional',
    'licorice',
    'perfume',
    'distinct lemon',
    'mild tart',
    'silky',
    'chewy',
    'cocoa butter dominates',
    'vanilla dominate',
    'mild metallic and spice',
    'mild intensity',
    'smoke',
    'cocoa base',
    'fudgey',
    'ashey',
    'mild strawberry',
    'slight cherry',
    'cocoa tea',
    'mild grape',
    'bubblegum',
    'chocolate and grapes',
    'hint of fruit',
    'sugary',
    'bold citrus',
    'burnt up front',
    'plastic off note',
    'coffee',
    'bitter',
    'earthen',
    'oily surface',
    'strong nutty with off notes',
    'palm',
    'unpleasant',
    'late cocoa',
    'well defined',
    'choco',
    'oats',
    'single note of cocoa',
    'malt',
    'black licorice',
    'strong tobacco',
    'muted',
    'grain',
    'late choco',
    'mild nuts',
    'off notes',
    'apple',
    'tropical berry',
    'mild fruit and spice',
    'late sour',
    'very roasty',
    'hint of berry',
    'bitter ending',
    'intense fruit',
    'rasin',
    'dirt/ earthy',
    'molasses notes dominate',
    'near perfect shine',
    'metallic',
    'well developed',
    'hot spices',
    'berry',
    'dark coffee',
    'raw',
    'texture issues',
    'odd rubber notes',
    'nice melt',
    'strong sour',
    'peanut',
    'sunflower',
    'sweet spice',
    'hints of fruit',
    'soap',
    'holiday spice',
    'dark woody',
    'dry',
    'cocoa flavor dominates',
    'distinct choco and graham',
    'basic fudgey',
    'faint fruit',
    'orange soda',
    'choco pudding',
    'leafy',
    'atypical',
    'ripe orange',
    'moderate acidity',
    'oreo shell',
    'candy spice',
    'tannic',
    'slight anise',
    'sour cherry',
    'fresh fruit',
    'odd',
    'harsh woody/green',
    'sour coffee',
    'intense orange',
    'mass market',
    'synthetic',
    'full flavor w/ dominant roast',
    'high intensity bitter',
    'candy like vanilla',
    'rich malt',
    'cigarette butt',
    'basic cocoa base',
    'deep cherry',
    'true to sugar',
    'off fatty note',
    'light lime',
    'sweet',
    'rich cocoa',
    'coffee and cocoa',
    'cardboard off',
    'early fruit',
    'subtle peanut butter',
    'mild choco & leather',
    'banana raspberry',
    'earthy off notes',
    'fruity then nutty',
    'almond',
    'perfectly balanced roast',
    'mild',
    'coffee AT',
    'hint of lemon',
    'classic brownie',
    'hit of anise',
    'whole bean',
    'floral notes'
];